Repository Azure/aml-deploy, pull requests merged in 2020-05, with the labels that each got.

#7 Added input validation and & tests
  .cloud/.azure/aci_deploy.json
  .cloud/.azure/aks_deploy.json
  .cloud/.azure/deploy.json
  .github/workflows/python.yml
  .gitignore
  Dockerfile
  README.md
  code/entrypoint.sh
  code/main.py
  code/schemas.py
  code/utils.py
  tests/test_main.py
  tests/test_utils.py
Labels: enhancement

#9 Ashishonce/integration tests
  .cloud/.azure/test/test_aci_deploy.json
  .cloud/.azure/test/test_aks_deploy.json
  .cloud/.azure/test/test_workspace.json
  .github/workflows/integration.yml
  tests/deploy/environment.yml
  tests/deploy/score.py
Labels: enhancement

#10 updating readme
  README.md
Labels: documentation

#11 Update azureml-sdk to 1.5.0
  Dockerfile
Labels: enhancement

#12 remove ls
  .gitattributes
  CODE_OF_CONDUCT.md
  LICENSE
  SECURITY.md
  code/entrypoint.sh
Labels: bug

#14 Upgrade to Azure ML SDK 1.6.0
  Dockerfile
Labels: enhancement
